### ISSUE TITLE
/hr Slack Command

### ISSUE THREAD

**Issue by mehdipiraee** [FocusedDiversity/synaptiq-melvil#26]
```[tasklist]
### Tasks
- [ ] https://github.com/FocusedDiversity/synaptiq-hppo/issues/27
- [ ] https://github.com/FocusedDiversity/synaptiq-hppo/issues/28
- [ ] https://github.com/FocusedDiversity/synaptiq-hppo/issues/29
- [ ] https://github.com/FocusedDiversity/hippo/issues/3
- [ ] Security governance concerns to address for the demo
```
